

assigning a variable with the <- assignment operator

vectors define
c() is the combine function that creates vectors 
length() will determine number of members in a vector


typeof() determines the data type
boolean checks of datatypes - is.logical() / is.integer() / etc.


Data frame is a collection of columns of data - basically an R equivalent of a spreadsheet or SQL table. Columns must have names, every cell must have content, and there can only be one element per cell. 
data.frame() will create a data frame, and takes vectors as inputs.

```{r}
data.frame(x = c(1,2,3), y = c(4,5,6))
```

file.create() creates a new file, returns a boolean based on success or failure of file creation.
file.copy() copies a file
unlink() deletes a file


A matrix is a two dimensional vector, and must contain only one datatype throughout.


arrays define
lists define


Pipes are useful for scripting multiple operations in a row. The pipeline operator '%>%' is used at the end of each line except the final line of commands.

tibbles are similar to data frames, but do not change the data type of inputs, variable names, they do not create row names, and essentially just make printing information to the console easier.

Remember that R functions are case sensitive! view() and View() are not the same function!
